<?xml version="1.0" encoding="utf-8"?>
<LevelData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <tiles>
    <Vector2>
      <x>8</x>
      <y>-10</y>
    </Vector2>
    <Vector2>
      <x>8</x>
      <y>-9</y>
    </Vector2>
    <Vector2>
      <x>8</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>8</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>8</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>8</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>7</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>7</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>7</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>7</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>7</x>
      <y>-9</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>-9</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>-9</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>-9</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>-10</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>-10</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>-10</y>
    </Vector2>
    <Vector2>
      <x>7</x>
      <y>-10</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>2</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>2</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>2</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>1</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>0</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>0</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>0</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>1</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>-2</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>-9</y>
    </Vector2>
    <Vector2>
      <x>-4</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-6</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-8</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-9</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-9</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>-9</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>-9</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>-9</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>-8</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-4</y>
    </Vector2>
    <Vector2>
      <x>-6</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>-4</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>-3</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>-6</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>-6</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>2</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>3</y>
    </Vector2>
    <Vector2>
      <x>-4</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>-3</y>
    </Vector2>
    <Vector2>
      <x>-2</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>-2</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>-2</x>
      <y>-3</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>-3</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>-4</y>
    </Vector2>
    <Vector2>
      <x>0</x>
      <y>-3</y>
    </Vector2>
    <Vector2>
      <x>1</x>
      <y>-3</y>
    </Vector2>
    <Vector2>
      <x>1</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>1</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>0</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>2</y>
    </Vector2>
    <Vector2>
      <x>0</x>
      <y>2</y>
    </Vector2>
    <Vector2>
      <x>1</x>
      <y>2</y>
    </Vector2>
    <Vector2>
      <x>2</x>
      <y>2</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>2</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>2</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>3</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>4</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>5</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>5</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>5</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>5</y>
    </Vector2>
    <Vector2>
      <x>2</x>
      <y>5</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>-1</y>
    </Vector2>
  </tiles>
  <coins>
    <Vector2>
      <x>3</x>
      <y>5</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>-4</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>-1</y>
    </Vector2>
  </coins>
  <dots>
    <Vector2>
      <x>6</x>
      <y>-9</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>2</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>2</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>1</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>0</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>0</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>0</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>1</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>2</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>-2</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>-4</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-6</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-8</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-9</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>-9</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>-9</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>-9</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>-8</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>-6</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>-4</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>-3</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>-6</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>-6</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>-4</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>-3</x>
      <y>-3</y>
    </Vector2>
    <Vector2>
      <x>-2</x>
      <y>-3</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>-3</y>
    </Vector2>
    <Vector2>
      <x>0</x>
      <y>-3</y>
    </Vector2>
    <Vector2>
      <x>1</x>
      <y>-3</y>
    </Vector2>
    <Vector2>
      <x>1</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>1</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>0</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>-2</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>2</y>
    </Vector2>
    <Vector2>
      <x>0</x>
      <y>2</y>
    </Vector2>
    <Vector2>
      <x>1</x>
      <y>2</y>
    </Vector2>
    <Vector2>
      <x>2</x>
      <y>2</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>2</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>-1</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>1</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>2</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>3</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>4</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>5</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>5</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>5</y>
    </Vector2>
  </dots>
  <dangers>
    <Vector2>
      <x>9</x>
      <y>-10</y>
    </Vector2>
    <Vector2>
      <x>9</x>
      <y>-9</y>
    </Vector2>
    <Vector2>
      <x>9</x>
      <y>-8</y>
    </Vector2>
    <Vector2>
      <x>9</x>
      <y>-7</y>
    </Vector2>
    <Vector2>
      <x>9</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>9</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>-10</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>-6</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>-4</y>
    </Vector2>
    <Vector2>
      <x>4</x>
      <y>-4</y>
    </Vector2>
    <Vector2>
      <x>5</x>
      <y>-4</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>-4</y>
    </Vector2>
    <Vector2>
      <x>7</x>
      <y>-4</y>
    </Vector2>
    <Vector2>
      <x>8</x>
      <y>-4</y>
    </Vector2>
    <Vector2>
      <x>9</x>
      <y>-4</y>
    </Vector2>
    <Vector2>
      <x>-1</x>
      <y>-5</y>
    </Vector2>
  </dangers>
  <birds>
    <Vector2>
      <x>-3</x>
      <y>-9</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-4</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>0</y>
    </Vector2>
    <Vector2>
      <x>3</x>
      <y>1</y>
    </Vector2>
  </birds>
  <birds2>
    <Vector2>
      <x>-3</x>
      <y>-5</y>
    </Vector2>
    <Vector2>
      <x>-7</x>
      <y>-9</y>
    </Vector2>
    <Vector2>
      <x>-5</x>
      <y>3</y>
    </Vector2>
    <Vector2>
      <x>6</x>
      <y>1</y>
    </Vector2>
  </birds2>
</LevelData>